---
- name: configure k8 master
  hosts: k8[0]
  become: true
  roles:
    - role: sfactory
      tags: sfactory
    - role: master
      tags: master
    - role: join_master
      tags: join_master  

- name: configure k8 worker
  hosts: k8[1]
  become: true
  roles:
    - role: join_worker
      tags: join_worker  
